name: Bug Report
description: When a feature is not behaving as expected.
labels: [bug]
assignees: code807,quellus
body:
  - type: textarea
    id: Describe
    attributes:
      label: Describe the bug?
      description: A clear and concise description of what the bug is?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add media to help explain your problem
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Godot Version
      placeholder: 1.2.3 (USE AN ACTUAL VERSION NUMBER)
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: What Platforms does this occur on?
      multiple: true
      options:
        - "Windows"
        - "Linux"
        - "macOS"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false